---Event.lua


-- We agree that the events received by the script use the "EVENT" prefix.
-- Events sent to the UI by scripts use the "UI" prefix, and events sent to the
-- global use the "GLOBAL" prefix

---@class Event
local Event = {
    EVENT_EXIT = "EVENT_EXIT",
    EVENT_LEVEL_SELECT_PAGE_UP = "EVENT_LEVEL_SELECT_PAGE_UP",
    EVENT_LEVEL_SELECT_PAGE_DOWN = "EVENT_LEVEL_SELECT_PAGE_DOWN",
    UI_SHOW_LEVEL_SELECT_UI = "UI_SHOW_LEVEL_SELECT_UI",
    UI_HIDE_LEVEL_SELECT_UI = "UI_HIDE_LEVEL_SELECT_UI",
    UI_SHOW_LOAD_UI = "UI_SHOW_LOAD_UI",
    UI_HIDE_LOAD_UI = "UI_HIDE_LOAD_UI",
    UI_SHOW_GAME_UI = "UI_SHOW_GAME_UI",
    UI_HIDE_GAME_UI = "UI_HIDE_GAME_UI",

    EVENT_GAME_OPERATION_TOUCH = "EVENT_GAME_OPERATION_TOUCH",
    EVENT_GAME_OPERATION_TOUCH_RELEASE = "EVENT_GAME_OPERATION_TOUCH_RELEASE",

    UI_PLAY_LEVEL_SWITCH_ANIM_IN = "UI_PLAY_LEVEL_SWITCH_ANIM_IN",
    UI_PLAY_LEVEL_SWITCH_ANIM_OUT = "UI_PLAY_LEVEL_SWITCH_ANIM_OUT",

    EVENT_GAME_RUN_LEVEL = "EVENT_GAME_RUN_LEVEL",

    UI_SHOW_LEVEL_SWITCH_SCENE = "UI_SHOW_LEVEL_SWITCH_SCENE",
    UI_HIDE_LEVEL_SWITCH_SCENE = "UI_HIDE_LEVEL_SWITCH_SCENE",

    EVENT_LEVEL_SELECT_TOUCH = "EVENT_LEVEL_SELECT_TOUCH",
    EVENT_EXIT_GAME = "EVENT_EXIT_GAME",

    EVENT_GAME_CAMERA_ZOOM_IN = "EVENT_GAME_CAMERA_ZOOM_IN",
    EVENT_GAME_CAMERA_ZOOM_OUT = "EVENT_GAME_CAMERA_ZOOM_OUT",
    GLOBAL_GRADUAL_SET_CAMERA_DISTANCE = "GLOBAL_GRADUAL_SET_CAMERA_DISTANCE",

    EVENT_GAME_OPERATION_DELETE_MODE = "EVENT_GAME_OPERATION_DELETE_MODE",
    EVENT_GAME_OPERATION_CREATE_MODE = "EVENT_GAME_OPERATION_CREATE_MODE",

    UI_GAME_SHOW_DELETE_MODE = "UI_GAME_SHOW_DELETE_MODE",
    UI_GAME_HIDE_DELETE_MODE = "UI_GAME_HIDE_DELETE_MODE",

}
return Event
