local Global = {
    LOGIC_FPS = 30,
    LOGIC_FRAME_INTERVAL = 1.0 / 30,

    LEVEL_SELECTOR_PAGE_REFERENCE_POINT = math.Vector3(450, 54.5, -800),
    LEVEL_SELECTOR_PAGE_SPACING = 110.0,
    LEVEL_SELECTOR_PAGE_SWITCH_DURATION = 0.3,

    LOAD_UI_FADE_IN_OUT_TIME = 0.3,
    LEVEL_PAGE_COUNT = 13,
    LEVEL_SWITCH_ANIM_IN_OUT_DURATION = 1.0,

    GAME_CAMERA_CENTER_REFERENCE_POINT = math.Vector3(0, 0, 0),
    GAME_GRID_SIZE = 10.0,
    GAME_GRID_LOOP_FRAME_COUNT = 15,

    GAME_CAMERA_MAX_DISTANCE = 180.0,
    GAME_CAMERA_MIN_DISTANCE = 90.0
}


return Global
