local Global = {
    LOGIC_FPS = 30,
    LOGIC_FRAME_INTERVAL = 1.0 / 30,

    LEVEL_SELECTOR_PAGE_REFERENCE_POINT = math.Vector3(0, 50, -800),
    LEVEL_SELECTOR_PAGE_SPACING = 10.0,
    LEVEL_SELECTOR_PAGE_SWITCH_DURATION = 0.3,

    LOAD_UI_FADE_IN_OUT_TIME = 0.4
}


return Global
