local Global = {
    LOGIC_FPS = 30,
    LOGIC_FRAME_INTERVAL = 1.0 / 30,

    LEVEL_SELECTOR_PAGE_REFERENCE_POINT = math.Vector3(450, 54.5, -750),
    LEVEL_SELECTOR_PAGE_SPACING = 110.0,
    LEVEL_SELECTOR_PAGE_SWITCH_DURATION = 0.3,

    LOAD_UI_FADE_IN_OUT_TIME = 0.4,
    LEVEL_PAGE_COUNT = 13,
    LEVEL_SWITCH_ANIM_IN_OUT_DURATION = 0.4,

    GAME_CAMERA_CENTER_REFERENCE_POINT = math.Vector3(0, 0, 0)
}


return Global
