local UI = {
    LEVEL_SELECT_PROGRESS_BAR = "1519736575|1354614584",
    GAME_RAIL_COUNT = "",
    GAME_RAIL_OPERATION_PUT = "",
    GAME_RAIL_OPERATION_COLLECT = "",
    GAME_LEVEL_NAME_LABEL = "",
}

return UI
